import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import fs from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {useTestDatabase,query} from '../lib/db.js';
import {migrate} from '../scripts/migrate.mjs';
import {seed} from '../scripts/seed.mjs';
import * as s from '../lib/service.js';
import {weighted,criterionIndex,stage,calculate} from '../lib/scoring.js';
import {passwordHash,passwordMatches} from '../lib/auth.js';
import {validateFile} from '../lib/evidence-storage.js';
import {pdfReport} from '../lib/report.js';
import {mirrorRows} from '../lib/sheets-sync.js';
import {frameworkSchema} from '../lib/validation.js';
import {createServer} from 'node:http';
import handler from '../api/index.js';
let db,admin,outsider,client,a,framework;
before(async()=>{process.env.NODE_ENV='test';db=new PGlite();useTestDatabase(db);await migrate();await seed('qa@example.test','OnlyForAutomatedTest-49!');admin=(await query('SELECT * FROM users LIMIT 1')).rows[0];outsider={id:randomUUID(),is_admin:false};client=await s.createClient(admin,{name:'Synthetic QA Organization',sector:'Testing'});framework=(await query("SELECT * FROM frameworks WHERE module_id='strategy'")).rows[0];await s.activateModule(admin,client.id,{module_id:'strategy',enabled:true});a=await s.createAssessment(admin,{client_id:client.id,title:'Synthetic validation assessment',assessment_date:'2026-09-28',framework_ids:[framework.id]});});
after(async()=>db.close());
test('Draft framework definitions pass publication validation',async()=>{for(const f of (await query("SELECT * FROM frameworks WHERE status='Draft'")).rows)frameworkSchema.parse({module_id:f.module_id,version:f.version,definition:f.definition});});
test('complete review workflow freezes scores and creates an export outbox',async()=>{
  const fresh=await s.createAssessment(admin,{client_id:client.id,title:'Complete synthetic lifecycle',assessment_date:'2026-09-28',framework_ids:[framework.id]});
  for(let r of (await s.assessmentDetail(admin,fresh.id)).responses){const c=framework.definition.domains.flatMap(d=>d.criteria).find(c=>c.id===r.criterion_id);
    r=await s.saveResponse(admin,fresh.id,r.id,{revision:r.revision,answers:{[c.questions[0].id]:3},comment:'Synthetic validation',internal_notes:'NEVER EXPORTED',confidence:'High',confidence_rationale:'Controlled test evidence'});
    const ev=await s.addEvidence(admin,fresh.id,{title:'Synthetic test record',kind:'Interview notes',description:'Corroborated QA practice',source:'QA',owner:'QA',evidence_date:null,url:null,response_ids:[r.id]});
    await s.reviewEvidence(admin,fresh.id,ev.id,{revision:0,verification_status:'Verified',strength:'High',reviewer_comments:'Verified synthetic test record'});
    r=(await s.assessmentDetail(admin,fresh.id)).responses.find(x=>x.id===r.id);
    r=await s.setTarget(admin,fresh.id,r.id,{revision:r.revision,target:3,rationale:'Maintain current synthetic level'});
    await s.reviewResponse(admin,fresh.id,r.id,{revision:r.revision,score:3,status:'Approved',rationale:'Confirmed against test evidence'});
  }
  for(const status of ['Data Collection','Assessment in Progress','Evidence Review','Calibration','Management Review','Approved','Closed']){const d=await s.assessmentDetail(admin,fresh.id);await s.changeStatus(admin,fresh.id,{revision:d.assessment.revision,status,reason:'Synthetic workflow validation'});}
  const report=await s.report(admin,fresh.id);assert.equal(report.results.score,'3');assert.equal(report.results.target,'3');assert.equal(report.approved,true);assert.ok(!JSON.stringify(report).includes('NEVER EXPORTED'));
  const snapshots=(await query('SELECT * FROM report_snapshots WHERE assessment_id=$1',[fresh.id])).rows;assert.equal(snapshots.length,1);assert.equal((await query('SELECT * FROM sync_outbox WHERE snapshot_id=$1',[snapshots[0].id])).rows.length,1);
  await assert.rejects(query('UPDATE report_snapshots SET report=$1 WHERE id=$2',['{}',snapshots[0].id]),/Append-only/);
  const rows=mirrorRows(snapshots);assert.equal(rows.assessments.length,2);assert.equal(rows.responses.length,11);assert.ok(!JSON.stringify(rows).includes('NEVER EXPORTED'));assert.equal((await s.compareAssessments(admin,fresh.id,fresh.id)).rows[0].change,0);
  const rr=(await s.assessmentDetail(admin,fresh.id)).responses[0];await assert.rejects(s.setTarget(admin,fresh.id,rr.id,{revision:rr.revision,target:5,rationale:'Attempt mutation'}),/locked/);
});
test('HTTP authentication and CSRF reject unauthorized mutations',async()=>{
  const server=createServer(handler);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;process.env.APP_ORIGIN=origin;
  try{assert.equal((await fetch(origin+'/api/bootstrap')).status,401);assert.equal((await fetch(origin+'/api/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://foreign.example'},body:JSON.stringify({email:'qa@example.test',password:'OnlyForAutomatedTest-49!'})})).status,403);
    const login=await fetch(origin+'/api/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({email:'qa@example.test',password:'OnlyForAutomatedTest-49!'})});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0];
    const boot=await (await fetch(origin+'/api/bootstrap',{headers:{Cookie:cookie}})).json();assert.ok(boot.csrf);assert.equal((await fetch(origin+'/api/clients',{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'},body:'{"name":"blocked","sector":"QA"}'})).status,403);
  }finally{await new Promise(resolve=>server.close(resolve));}
});
test('weighted reference cases: minimum, maximum, mixed; no missing-as-zero',()=>{const weights=[.25,.2,.2,.2,.15];for(const [ratings,expected] of [[[1,1,1,1,1],'1'],[[5,5,5,5,5],'5'],[[1,2,3,4,5],'2.8']])assert.equal(weighted(ratings.map((score,i)=>({score,weight:weights[i]}))),expected);assert.equal(weighted([{score:1,weight:1},{score:null,weight:1}]),null);assert.throws(()=>weighted([{score:0,weight:1}]));});
test('criterion supports multiple weighted questions',()=>assert.equal(criterionIndex({questions:[{id:'a',weight:1},{id:'b',weight:3}]},{a:1,b:5}),'4'));
test('only explicit approved gates cap a stage; low noncritical score does not',()=>{const bands=[1,2,3,4,5].map(level=>({level,minimum:level}));const criteria=[{id:'ordinary',score:1},{id:'critical',score:2}];assert.equal(stage('4.2',criteria,{bands,gates:[]}).level,4);const gate={criterionId:'critical',minimum:3,cap:2,status:'Approved',source:'Reviewed test framework',rationale:'Required authority absent'};assert.equal(stage('4.2',criteria,{bands,gates:[gate]}).level,2);assert.equal(stage('4.2',criteria,{bands,gates:[{...gate,status:'Draft'}]}).level,4);assert.equal(stage('4.2',criteria).level,null);});
test('Draft modules cannot be activated or assessed',async()=>{await assert.rejects(s.activateModule(admin,client.id,{module_id:'pmo',enabled:true}),/no approved framework/);const draft=(await query("SELECT id FROM frameworks WHERE module_id='pmo'")).rows[0];await assert.rejects(s.createAssessment(admin,{client_id:client.id,title:'Blocked',assessment_date:'2026-09-28',framework_ids:[draft.id]}),/approved/);});
test('cross-client reads and writes denied',async()=>{await assert.rejects(s.assessmentDetail(outsider,a.id),/access/);await assert.rejects(s.createAssessment(outsider,{client_id:client.id,title:'Blocked',assessment_date:'2026-09-28',framework_ids:[framework.id]}),/access/);});
test('responses persist, reject stale revisions and retain null targets',async()=>{const detail=await s.assessmentDetail(admin,a.id);const r=detail.responses[0];const c=framework.definition.domains.flatMap(d=>d.criteria).find(c=>c.id===r.criterion_id);const body={revision:0,answers:{[c.questions[0].id]:3},comment:'QA record',internal_notes:'INTERNAL SECRET QA',confidence:'Medium',confidence_rationale:'Interview requires corroboration'};const saved=await s.saveResponse(admin,a.id,r.id,body);assert.equal(Number(saved.consultant_score),3);assert.equal(saved.target,null);assert.equal(saved.revision,1);await assert.rejects(s.saveResponse(admin,a.id,r.id,body),/record changed/);assert.equal((await s.assessmentDetail(admin,a.id)).responses.find(x=>x.id===r.id).comment,'QA record');});
test('approval requires verified evidence; evidence changes invalidate reviews',async()=>{let r=(await s.assessmentDetail(admin,a.id)).responses[0];await assert.rejects(s.reviewResponse(admin,a.id,r.id,{revision:r.revision,score:3,status:'Approved',rationale:'QA review'}),/Verified evidence/);const ev=await s.addEvidence(admin,a.id,{title:'QA interview',kind:'Interview notes',description:'Observed practice record',source:'Synthetic test',owner:'QA',evidence_date:'2026-09-28',url:null,response_ids:[r.id]});await s.reviewEvidence(admin,a.id,ev.id,{revision:0,verification_status:'Verified',strength:'Medium',reviewer_comments:'Corroborated synthetic interview'});r=(await s.assessmentDetail(admin,a.id)).responses[0];r=await s.reviewResponse(admin,a.id,r.id,{revision:r.revision,score:3,status:'Approved',rationale:'Matches level 3'});assert.equal(r.review_status,'Approved');await s.reviewEvidence(admin,a.id,ev.id,{revision:1,verification_status:'Rejected',strength:'Low',reviewer_comments:'New contradiction found'});r=(await s.assessmentDetail(admin,a.id)).responses[0];assert.equal(r.review_status,'Pending');assert.equal(r.reviewer_score,null);});
test('tenant-safe evidence links reject unrelated responses and roll back',async()=>{const other=await s.createClient(admin,{name:'Other QA client',sector:'Testing'});await s.activateModule(admin,other.id,{module_id:'strategy',enabled:true});const aa=await s.createAssessment(admin,{client_id:other.id,title:'Other',assessment_date:'2026-09-28',framework_ids:[framework.id]});const rr=(await s.assessmentDetail(admin,aa.id)).responses[0];const before=Number((await query('SELECT count(*) n FROM evidence')).rows[0].n);await assert.rejects(s.addEvidence(admin,a.id,{title:'Bad link',kind:'Interview notes',description:'Invalid',source:'QA',owner:'QA',evidence_date:null,url:null,response_ids:[rr.id]}),/not found/);assert.equal(Number((await query('SELECT count(*) n FROM evidence')).rows[0].n),before);});
test('client report excludes internal notes; PDF is generated',async()=>{const r=await s.report(admin,a.id);assert.ok(!JSON.stringify(r).includes('INTERNAL SECRET QA'));assert.equal(r.results.score,null);const pdf=await pdfReport(r);assert.equal(pdf.subarray(0,5).toString(),'%PDF-');assert.ok(pdf.length>1000);});
test('frameworks and audit records are immutable at database layer',async()=>{await assert.rejects(query("UPDATE frameworks SET version='bad' WHERE id=$1",[framework.id]),/immutable/);await assert.rejects(query("DELETE FROM audit_events"),/Append-only/);});
test('invalid uploads and passwords are checked',async()=>{assert.throws(()=>validateFile({name:'x.pdf',mime:'application/pdf',base64:Buffer.from('not a PDF').toString('base64')}),/Unsupported/);const h=await passwordHash('A long QA password');assert.ok(await passwordMatches('A long QA password',h));assert.equal(await passwordMatches('incorrect',h),false);});
test('workflow cannot skip final review; aggregation keeps modules separate',async()=>{const d=await s.assessmentDetail(admin,a.id);await assert.rejects(s.changeStatus(admin,a.id,{revision:d.assessment.revision,status:'Approved',reason:'Try to skip'}),/next lifecycle/);const answers=framework.definition.domains.flatMap(domain=>domain.criteria.map(c=>({criterion_id:c.id,consultant_score:5,target:null,review_status:'Pending'})));const result=calculate([framework],answers);assert.equal(result.score,'5');assert.equal(result.target,null);assert.equal(result.stage.level,null);});
