import PDFDocument from 'pdfkit';
import {display} from './scoring.js';
export function pdfReport(report){
  return new Promise(resolve=>{const doc=new PDFDocument({size:'A4',margin:48,bufferPages:true});const chunks=[];doc.on('data',x=>chunks.push(x));doc.on('end',()=>resolve(Buffer.concat(chunks)));
    const line=(s,size=10)=>{doc.fontSize(size).fillColor('#24344b').text(String(s));doc.moveDown(.45);};
    doc.rect(0,0,595,130).fill('#102d3d');doc.fillColor('white').fontSize(11).text('MATURITY INTELLIGENCE / CLIENT REPORT',48,40);doc.fontSize(25).text(report.client.name,48,65);doc.y=155;
    line(report.assessment.title,18);line(`Assessment date: ${String(report.assessment.assessment_date).slice(0,10)}`);line(`Report status: ${report.approved?'Approved':'Working draft — not a final assessment'}`);line('Client branding: add approved client identity before distribution.');
    line('Executive summary',17);line(`Overall weighted index: ${display(report.results.score)??'Incomplete'} / 5`);line(`Target: ${display(report.results.target)??'Not set'}    Gap: ${display(report.results.gap)??'Not available'}`);line('Stage: '+(report.results.stage?.level??'No approved overall stage policy'));
    line('Maturity profile',17);
    for(const m of report.results.modules){line(m.title,14);for(const d of m.domains){line(`${d.title}: ${display(d.score)??'Incomplete'} | target ${display(d.target)??'Not set'} | gap ${display(d.gap)??'Not available'}`);for(const c of d.criteria)line(`  ${c.title}: ${display(c.score)??'Unrated'} — confidence ${c.confidence??'Unclassified'}`,9);}}
    for(const [title,records] of [['Findings',report.findings],['Recommendations and implementation',report.recommendations],['Improvement roadmap',report.roadmap]]){doc.addPage();line(title,20);if(!records.length)line('No approved content recorded.');for(const r of records){line(r.title,13);for(const key of ['description','condition','root_cause','consequence','action','rationale','approach','deliverables','objective','actions','deliverable','owner','priority','horizon','source_location'])if(r[key])line(`${key.replaceAll('_',' ')}: ${r[key]}`);if(r.start_month!=null)line(`Months ${r.start_month}–${r.end_month}`);}}
    doc.addPage();line('Recommended assets and KPIs',18);for(const k of report.assets||[]){line(k.title,12);line(k.description);line(k.content?.formula||'');line('Target: '+(k.content?.target||'Baseline required before target setting'));line(k.source_url||k.source_section||'Source not recorded');}if(!report.assets?.length)line('No approved assets linked.');line('Methodology and provenance',18);line('Weighted index based on approved framework versions. No N/A and no automatic targets. Critical criteria gates apply only where explicitly approved. This is not an official CMMI appraisal or ISO certification.');for(const f of report.frameworks)line(`${f.definition.title} — ${f.version}`);line('Expected impact is qualitative unless supported by verified evidence. Internal consultant notes are excluded.');
    const pages=doc.bufferedPageRange();for(let i=0;i<pages.count;i++){doc.switchToPage(i);doc.fontSize(8).fillColor('#667085').text(`Confidential | ${report.client.name} | ${i+1} / ${pages.count}`,48,790,{lineBreak:false});}doc.end();
  });
}
