import {randomUUID} from 'node:crypto';
import {query,transaction} from './db.js';
import {fail,clientAccess,passwordHash} from './auth.js';
import * as v from './validation.js';
import {z} from 'zod';
import {calculate,criterionIndex} from './scoring.js';
import {storeFile,removeFile} from './evidence-storage.js';
const mutableRoles=['lead','consultant'];
const lifecycle=['Draft','Data Collection','Assessment in Progress','Evidence Review','Calibration','Management Review','Approved','Closed'];
const json=x=>JSON.stringify(x);
async function insert(db,table,obj){const keys=Object.keys(obj);await db.query(`INSERT INTO ${table}(${keys.join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')})`,Object.values(obj));return obj;}
export async function audit(db,user,action,entity,before,after,clientId=null,assessmentId=null,reason=''){
  await insert(db,'audit_events',{id:randomUUID(),client_id:clientId,assessment_id:assessmentId,actor_id:user.id,action,entity_id:String(entity),previous_value:before==null?null:json(before),new_value:after==null?null:json(after),reason});
}
async function assessment(db,user,id,roles=[],lock=false){v.id.parse(id);const {rows}=await db.query('SELECT * FROM assessments WHERE id=$1'+(lock?' FOR UPDATE':''),[id]);if(!rows[0])fail(404,'Assessment not found');await clientAccess(db,user,rows[0].client_id,roles);return rows[0];}
function editable(a){if(['Approved','Closed'].includes(a.status))fail(409,'This assessment is locked. Create a new assessment to preserve history.');}
async function mutate(user,id,roles,fn,allowClosed=false){return transaction(async db=>{const a=await assessment(db,user,id,roles,true);if(!allowClosed)editable(a);const result=await fn(db,a);await db.query('UPDATE assessments SET revision=revision+1 WHERE id=$1',[a.id]);return result;});}
async function invalidateConclusions(db,responseId){await db.query("UPDATE findings SET review_status='Draft' WHERE response_id=$1",[responseId]);await db.query("UPDATE recommendations SET status='Draft',approved_by=null WHERE response_id=$1",[responseId]);}
async function frameworksFor(db,id){return (await db.query('SELECT f.*,am.weight FROM assessment_modules am JOIN frameworks f ON f.id=am.framework_id WHERE am.assessment_id=$1 ORDER BY f.module_id',[id])).rows;}
async function response(db,a,id){v.id.parse(id);const {rows}=await db.query('SELECT * FROM responses WHERE id=$1 AND assessment_id=$2 AND client_id=$3',[id,a.id,a.client_id]);if(!rows[0])fail(404,'Response not found');return rows[0];}
function revision(old,expected){if(old.revision!==expected)fail(409,'This record changed. Reload before saving to avoid overwriting another user.');}
export async function bootstrap(user){
  const clients=(await query(user.is_admin?'SELECT * FROM clients ORDER BY name':'SELECT c.* FROM clients c JOIN memberships m ON c.id=m.client_id WHERE m.user_id=$1 ORDER BY c.name',user.is_admin?[]:[user.id])).rows;
  const assessments=(await query(user.is_admin?'SELECT a.*,c.name client_name FROM assessments a JOIN clients c ON c.id=a.client_id ORDER BY a.created_at DESC':'SELECT a.*,c.name client_name FROM assessments a JOIN clients c ON c.id=a.client_id JOIN memberships m ON c.id=m.client_id WHERE m.user_id=$1 ORDER BY a.created_at DESC',user.is_admin?[]:[user.id])).rows;
  const frameworks=(await query('SELECT * FROM frameworks ORDER BY module_id,version')).rows;
  const activations=(await query(user.is_admin?'SELECT * FROM client_modules':'SELECT cm.* FROM client_modules cm JOIN memberships m ON cm.client_id=m.client_id WHERE m.user_id=$1',user.is_admin?[]:[user.id])).rows;
  return {user:{id:user.id,name:user.name,email:user.email,is_admin:user.is_admin},csrf:user.csrf,clients,assessments,frameworks,activations,storage:{database:'PostgreSQL',evidence:!!process.env.BLOB_READ_WRITE_TOKEN,sheets:!!process.env.SHEET_ID},lifecycle};
}
export async function createClient(user,body){if(!user.is_admin)fail(403,'Administrator access required');const data=v.clientSchema.parse(body);return transaction(async db=>{const c=await insert(db,'clients',{id:randomUUID(),...data});await audit(db,user,'client.created',c.id,null,c,c.id);return c;});}
export async function activateModule(user,clientId,body){if(!user.is_admin)fail(403,'Administrator access required');v.id.parse(clientId);const {module_id,enabled}=z.object({module_id:z.string(),enabled:z.boolean()}).parse(body);return transaction(async db=>{if(enabled&&!(await db.query("SELECT id FROM frameworks WHERE module_id=$1 AND status='Approved'",[module_id])).rows.length)fail(409,'This module has no approved framework. Draft content cannot be activated.');await db.query('INSERT INTO client_modules(client_id,module_id,enabled) VALUES($1,$2,$3) ON CONFLICT(client_id,module_id) DO UPDATE SET enabled=$3',[clientId,module_id,enabled]);await audit(db,user,'module.activation',module_id,null,{enabled},clientId);return {ok:true};});}
export async function createAssessment(user,body){const data=v.assessmentSchema.parse(body);return transaction(async db=>{
  await clientAccess(db,user,data.client_id,['lead']);
  if(new Set(data.framework_ids).size!==data.framework_ids.length)fail(400,'Duplicate framework');
  const fs=(await db.query("SELECT f.* FROM frameworks f JOIN client_modules cm ON cm.module_id=f.module_id AND cm.client_id=$1 AND cm.enabled=true WHERE f.id=ANY($2::uuid[]) AND f.status='Approved'",[data.client_id,data.framework_ids])).rows;
  if(fs.length!==data.framework_ids.length||new Set(fs.map(f=>f.module_id)).size!==fs.length)fail(409,'Choose one approved, activated framework per module');
  const {framework_ids,...fields}=data;const a=await insert(db,'assessments',{id:randomUUID(),...fields,assessor_id:user.id});
  for(const f of fs){await insert(db,'assessment_modules',{assessment_id:a.id,framework_id:f.id,weight:1});for(const d of f.definition.domains)for(const c of d.criteria)await insert(db,'responses',{id:randomUUID(),assessment_id:a.id,client_id:a.client_id,criterion_id:c.id});}
  await audit(db,user,'assessment.created',a.id,null,{...a,framework_ids},a.client_id,a.id);return a;
});}
export async function assessmentDetail(user,id){const db={query};const a=await assessment(db,user,id);const frameworks=await frameworksFor(db,id);const responses=(await query('SELECT * FROM responses WHERE assessment_id=$1 ORDER BY criterion_id',[id])).rows;const tables={};for(const table of ['evidence','findings','recommendations','roadmap','lessons','audit_events'])tables[table]=(await query(`SELECT * FROM ${table} WHERE assessment_id=$1`,[id])).rows;
  const links=(await query('SELECT * FROM evidence_links WHERE assessment_id=$1',[id])).rows;const dependencies=(await query('SELECT * FROM roadmap_dependencies WHERE assessment_id=$1',[id])).rows;
  return {assessment:a,frameworks,responses,...tables,links,dependencies,results:calculate(frameworks,responses),approvedResults:calculate(frameworks,responses,true),role:await clientAccess(db,user,a.client_id)};
}
export async function saveResponse(user,assessmentId,responseId,body){const b=v.responseSchema.parse(body);return mutate(user,assessmentId,mutableRoles,async(db,a)=>{const r=await response(db,a,responseId);revision(r,b.revision);const fs=await frameworksFor(db,a.id),c=fs.flatMap(f=>f.definition.domains.flatMap(d=>d.criteria)).find(c=>c.id===r.criterion_id);if(Object.keys(b.answers).some(key=>!c.questions.some(q=>q.id===key)))fail(400,'Unknown question');const index=criterionIndex(c,b.answers);await invalidateConclusions(db,r.id);
  await db.query("UPDATE responses SET answers=$1,consultant_score=$2,comment=$3,internal_notes=$4,confidence=$5,confidence_rationale=$6,review_status='Pending',reviewer_score=null,reviewed_by=null,review_rationale='',revision=revision+1,updated_at=now() WHERE id=$7",[json(b.answers),index,b.comment,b.internal_notes,b.confidence,b.confidence_rationale,r.id]);await audit(db,user,'response.changed',r.id,r,{...b,consultant_score:index},a.client_id,a.id);return response(db,a,r.id);});}
export async function setTarget(user,assessmentId,responseId,body){const b=v.targetSchema.parse(body);return mutate(user,assessmentId,['lead'],async(db,a)=>{const r=await response(db,a,responseId);revision(r,b.revision);await invalidateConclusions(db,r.id);await db.query('UPDATE responses SET target=$1,target_rationale=$2,revision=revision+1 WHERE id=$3',[b.target,b.rationale,r.id]);await audit(db,user,'target.changed',r.id,{target:r.target},{target:b.target},a.client_id,a.id,b.rationale);return response(db,a,r.id);});}
export async function reviewResponse(user,assessmentId,responseId,body){const b=v.reviewSchema.parse(body);return mutate(user,assessmentId,['lead','reviewer'],async(db,a)=>{const r=await response(db,a,responseId);revision(r,b.revision);if(r.consultant_score==null)fail(409,'Complete the consultant assessment before review');if(b.status==='Approved'){
  const found=(await db.query("SELECT e.id FROM evidence e JOIN evidence_links l ON e.id=l.evidence_id WHERE l.response_id=$1 AND e.verification_status='Verified' AND (e.object_key IS NULL OR e.scan_status='Clean')",[r.id])).rows;
  if(!found.length)fail(409,'Verified evidence is required before approving a score');if(!r.confidence||!r.confidence_rationale)fail(409,'Record confidence and rationale before approval');}
  await invalidateConclusions(db,r.id);await db.query('UPDATE responses SET reviewer_score=$1,review_status=$2,review_rationale=$3,reviewed_by=$4,revision=revision+1 WHERE id=$5',[b.status==='Approved'?b.score:null,b.status,b.rationale,user.id,r.id]);await audit(db,user,'response.reviewed',r.id,r,b,a.client_id,a.id,b.rationale);return response(db,a,r.id);});}
export async function addEvidence(user,assessmentId,body){const b=v.evidenceSchema.parse(body);let stored;try{return await mutate(user,assessmentId,mutableRoles,async(db,a)=>{for(const rid of b.response_ids)await response(db,a,rid);if(b.kind==='URL'&&!b.url)fail(400,'URL evidence requires a URL');if(!b.file&&!b.description&&!b.url)fail(400,'Provide evidence content');const eid=randomUUID();stored=b.file?await storeFile(b.file,a.client_id,eid):null;const {file,response_ids,...fields}=b;const e=await insert(db,'evidence',{id:eid,assessment_id:a.id,client_id:a.client_id,...fields,...(stored||{}),created_by:user.id,scan_status:stored?'Quarantined':'Not applicable'});for(const rid of response_ids){await invalidateConclusions(db,rid);await insert(db,'evidence_links',{evidence_id:e.id,response_id:rid,assessment_id:a.id,client_id:a.client_id});await db.query("UPDATE responses SET review_status='Pending',reviewer_score=null,reviewed_by=null,revision=revision+1 WHERE id=$1",[rid]);}await audit(db,user,'evidence.created',eid,null,{...e,response_ids},a.client_id,a.id);return e;});}catch(e){if(stored)await removeFile(stored.object_key).catch(()=>{});throw e;}}
export async function reviewEvidence(user,assessmentId,evidenceId,body){const b=z.object({revision:z.number().int(),verification_status:z.enum(['Verified','Rejected']),strength:z.enum(['Low','Medium','High']),reviewer_comments:v.short,scan_attestation:v.text.optional()}).parse(body);return mutate(user,assessmentId,['reviewer','lead'],async(db,a)=>{const old=(await db.query('SELECT * FROM evidence WHERE id=$1 AND assessment_id=$2',[v.id.parse(evidenceId),a.id])).rows[0];if(!old)fail(404,'Evidence not found');revision(old,b.revision);if(old.object_key&&b.verification_status==='Verified'&&(!user.is_admin||!b.scan_attestation))fail(409,'An administrator must record the malware scan reference before releasing this file');await db.query('UPDATE evidence SET verification_status=$1,strength=$2,reviewer_comments=$3,scan_status=$4,revision=revision+1 WHERE id=$5',[b.verification_status,b.strength,b.reviewer_comments,old.object_key?(b.verification_status==='Verified'?'Clean':'Rejected'):'Not applicable',old.id]);await db.query("UPDATE responses SET reviewer_score=null,review_status='Pending',reviewed_by=null,revision=revision+1 WHERE id IN (SELECT response_id FROM evidence_links WHERE evidence_id=$1)",[old.id]);for(const link of (await db.query('SELECT response_id FROM evidence_links WHERE evidence_id=$1',[old.id])).rows)await invalidateConclusions(db,link.response_id);await audit(db,user,'evidence.reviewed',old.id,old,b,a.client_id,a.id,b.reviewer_comments);return {ok:true};});}
export async function addRecord(user,assessmentId,kind,body){const configs={findings:v.findingSchema,recommendations:v.recommendationSchema,roadmap:v.roadmapSchema,lessons:v.lessonSchema};const schema=configs[kind];if(!schema)fail(404,'Unknown record type');const b=schema.parse(body);return mutate(user,assessmentId,mutableRoles,async(db,a)=>{if(kind==='lessons'&&a.status!=='Closed')fail(409,'Lessons learned are captured after closing the assessment');if(kind!=='lessons')editable(a);
  if(b.response_id){const r=await response(db,a,b.response_id);if(kind==='findings'&&!(await db.query('SELECT evidence_id FROM evidence_links WHERE response_id=$1',[r.id])).rows.length)fail(409,'Link supporting evidence before recording a finding');if(kind==='recommendations'&&(r.target==null||(r.reviewer_score??r.consultant_score)==null||Number(r.target)<=Number(r.reviewer_score??r.consultant_score)))fail(409,'Recommendations require a recorded positive maturity gap');}
  if(kind==='roadmap'){const rec=(await db.query("SELECT id FROM recommendations WHERE id=$1 AND assessment_id=$2 AND status='Approved'",[b.recommendation_id,a.id])).rows[0];if(!rec)fail(409,'Approve the recommendation before adding its roadmap initiative');}
  const r=await insert(db,kind,{id:randomUUID(),assessment_id:a.id,client_id:a.client_id,...b,...(['findings','lessons'].includes(kind)?{created_by:user.id}:{})});await audit(db,user,kind+'.created',r.id,null,r,a.client_id,a.id);return r;},kind==='lessons');}
export async function approveRecord(user,assessmentId,kind,id,body){if(!['findings','recommendations'].includes(kind))fail(404,'Unknown approval type');const {reason}=z.object({reason:v.short}).parse(body);return mutate(user,assessmentId,['lead','reviewer'],async(db,a)=>{const old=(await db.query(`SELECT * FROM ${kind} WHERE id=$1 AND assessment_id=$2`,[v.id.parse(id),a.id])).rows[0];if(!old)fail(404,'Record not found');if(kind==='recommendations')await clientAccess(db,user,a.client_id,['lead']);await db.query(`UPDATE ${kind} SET ${kind==='findings'?"review_status='Approved'":"status='Approved',approved_by=$3"} WHERE id=$1 AND assessment_id=$2`,kind==='findings'?[id,a.id]:[id,a.id,user.id]);await audit(db,user,kind+'.approved',id,old,{status:'Approved'},a.client_id,a.id,reason);return {ok:true};});}
export async function proposeRecommendations(user,assessmentId){return mutate(user,assessmentId,mutableRoles,async(db,a)=>{const fs=await frameworksFor(db,a.id),rs=(await db.query('SELECT * FROM responses WHERE assessment_id=$1',[a.id])).rows;let count=0;for(const r of rs){const current=r.reviewer_score??r.consultant_score;if(current==null||r.target==null||Number(r.target)<=Number(current))continue;if((await db.query('SELECT id FROM recommendations WHERE assessment_id=$1 AND response_id=$2',[a.id,r.id])).rows.length)continue;const c=fs.flatMap(f=>f.definition.domains.flatMap(d=>d.criteria)).find(c=>c.id===r.criterion_id);const target=c.descriptors[String(r.target)];const rec=await insert(db,'recommendations',{id:randomUUID(),assessment_id:a.id,client_id:a.client_id,response_id:r.id,title:'Strengthen '+c.title,action:'Establish and demonstrate the target practice: '+target,rationale:`Current rating ${current}; assessor-defined target ${r.target}.`,approach:`1. Validate the gap with the practice owner.\n2. Design the required practice and approval arrangements.\n3. Pilot with representative work and collect evidence.\n4. Review effectiveness before wider adoption.`,deliverables:`Approved practice definition, accountable owner, pilot evidence and review record for ${c.title}.`,owner:'Owner to be assigned',priority:'Medium',impact:'Expected improvement in the assessed practice; benefit requires validation.',effort:'Assess with the practice owner',horizon:'Time horizon to be agreed',source_location:`${c.source.title} — ${c.source.location}; target descriptor ${r.target}. Authored draft implementation guidance.`});count++;await audit(db,user,'recommendation.proposed',rec.id,null,rec,a.client_id,a.id);}return {count};});}
export async function reportData(db,user,id,final=false){const a=await assessment(db,user,id);const frameworks=await frameworksFor(db,id),responses=(await db.query('SELECT * FROM responses WHERE assessment_id=$1',[id])).rows;
  const client=(await db.query('SELECT id,name,sector,country FROM clients WHERE id=$1',[a.client_id])).rows[0];const findings=(await db.query("SELECT title,description,condition,root_cause,consequence,severity,priority FROM findings WHERE assessment_id=$1 AND review_status='Approved'",[id])).rows;const recommendations=(await db.query("SELECT * FROM recommendations WHERE assessment_id=$1 AND status='Approved'",[id])).rows;const roadmap=(await db.query('SELECT * FROM roadmap WHERE assessment_id=$1',[id])).rows;const assets=(await db.query("SELECT DISTINCT k.* FROM knowledge k JOIN recommendation_assets ra ON ra.knowledge_id=k.id JOIN recommendations r ON r.id=ra.recommendation_id WHERE r.assessment_id=$1 AND r.status='Approved' AND k.verification_status='Verified'",[id])).rows;
  return {client,assessment:{id:a.id,title:a.title,assessment_date:a.assessment_date,status:a.status},frameworks:frameworks.map(f=>({id:f.id,version:f.version,definition:{title:f.definition.title}})),results:calculate(frameworks,responses,true),findings,recommendations,roadmap,assets,approved:final};
}
export async function report(user,id){await assessment({query},user,id);const snapshot=(await query('SELECT * FROM report_snapshots WHERE assessment_id=$1 ORDER BY approved_at DESC LIMIT 1',[id])).rows[0];return snapshot?.report??reportData({query},user,id);}
export async function changeStatus(user,id,body){const b=z.object({revision:z.number().int(),status:z.enum(lifecycle),reason:v.short}).parse(body);return mutate(user,id,['lead'],async(db,a)=>{revision(a,b.revision);const old=lifecycle.indexOf(a.status),next=lifecycle.indexOf(b.status);if(next!==old+1)fail(409,'Move to the next lifecycle stage in order');if(b.status==='Approved'){
    const result=await reportData(db,user,id,true);if(!result.results.complete)fail(409,'All criteria require approved scores before final approval');if(result.results.target==null)fail(409,'Record explicit targets before approving the final gap analysis');
    const unresolved=(await db.query("SELECT id FROM findings WHERE assessment_id=$1 AND review_status<>'Approved' UNION ALL SELECT id FROM recommendations WHERE assessment_id=$1 AND status<>'Approved'",[id])).rows;if(unresolved.length)fail(409,'Review all findings and recommendations before approval');
    const gaps=result.results.modules.flatMap(m=>m.domains.flatMap(d=>d.criteria)).filter(c=>Number(c.target)>Number(c.score));for(const c of gaps){const r=(await db.query('SELECT id FROM responses WHERE assessment_id=$1 AND criterion_id=$2',[id,c.id])).rows[0];if(!(await db.query("SELECT rr.id FROM recommendations rr JOIN roadmap rm ON rm.recommendation_id=rr.id WHERE rr.response_id=$1 AND rr.status='Approved'",[r.id])).rows.length)fail(409,'Each positive gap requires an approved recommendation and roadmap initiative');}
    result.assessment.status='Approved';const snapshot=await insert(db,'report_snapshots',{id:randomUUID(),assessment_id:id,assessment_revision:a.revision+1,approved_by:user.id,report:json(result)});await insert(db,'sync_outbox',{id:randomUUID(),snapshot_id:snapshot.id});
  }
  await db.query('UPDATE assessments SET status=$1 WHERE id=$2',[b.status,id]);await audit(db,user,'assessment.status',id,{status:a.status},{status:b.status},a.client_id,id,b.reason);return {ok:true};},true);}
export async function knowledge(user){return (await query('SELECT * FROM knowledge ORDER BY kind,title')).rows;}
export async function addKnowledge(user,body){if(!user.is_admin)fail(403,'Administrator access required');const b=z.object({kind:z.enum(['KPI','Tool','Template','Case Study','Source']),title:v.short,description:v.text,source_url:z.url().refine(u=>['https:','http:'].includes(new URL(u).protocol)).nullable(),source_section:v.short,source_type:v.short,content:z.record(z.string(),z.unknown())}).parse(body);return transaction(async db=>{const r=await insert(db,'knowledge',{id:randomUUID(),...b,content:json(b.content)});await audit(db,user,'knowledge.created',r.id,null,r);return r;});}
export async function verifyKnowledge(user,id,body){if(!user.is_admin)fail(403,'Administrator access required');const {reason}=z.object({reason:v.short}).parse(body);return transaction(async db=>{const old=(await db.query('SELECT * FROM knowledge WHERE id=$1',[v.id.parse(id)])).rows[0];if(!old)fail(404,'Knowledge item not found');if(old.kind==='Case Study'&&(!old.content.organization||!old.content.outcome||!old.source_url))fail(409,'Case studies require an organization, outcome and verifiable source');await db.query("UPDATE knowledge SET verification_status='Verified',verified_at=now() WHERE id=$1",[id]);await audit(db,user,'knowledge.verified',id,old,{status:'Verified'},null,null,reason);return {ok:true};});}
export async function users(user){if(!user.is_admin)fail(403,'Administrator access required');return {users:(await query('SELECT id,email,name,is_admin,active FROM users ORDER BY name')).rows,memberships:(await query('SELECT * FROM memberships')).rows};}
export async function createUser(user,body){if(!user.is_admin)fail(403,'Administrator access required');const b=z.object({email:z.email().toLowerCase(),name:v.short,password:z.string().min(12).max(128),client_id:v.id,role:z.enum(['lead','consultant','reviewer'])}).parse(body);const ph=await passwordHash(b.password);return transaction(async db=>{const u=await insert(db,'users',{id:randomUUID(),email:b.email,name:b.name,password_hash:ph});await insert(db,'memberships',{user_id:u.id,client_id:b.client_id,role:b.role});await audit(db,user,'user.created',u.id,null,{email:b.email,role:b.role},b.client_id);return {id:u.id};});}
export async function assignUser(user,body){if(!user.is_admin)fail(403,'Administrator access required');const b=z.object({user_id:v.id,client_id:v.id,role:z.enum(['lead','consultant','reviewer'])}).parse(body);return transaction(async db=>{await db.query('INSERT INTO memberships(user_id,client_id,role) VALUES($1,$2,$3) ON CONFLICT(client_id,user_id) DO UPDATE SET role=$3',[b.user_id,b.client_id,b.role]);await audit(db,user,'membership.changed',b.user_id,null,b,b.client_id);return {ok:true};});}
export async function saveFramework(user,body){if(!user.is_admin)fail(403,'Administrator access required');const b=v.frameworkSchema.parse(body);const ids=b.definition.domains.flatMap(d=>d.criteria.map(c=>c.id));if(new Set(ids).size!==ids.length)fail(400,'Duplicate criterion IDs');for(const d of b.definition.domains)for(const c of d.criteria){if(new Set(c.questions.map(q=>q.id)).size!==c.questions.length)fail(400,'Duplicate question IDs');}
  return transaction(async db=>{const f=await insert(db,'frameworks',{id:randomUUID(),module_id:b.module_id,version:b.version,status:'Draft',definition:json(b.definition)});await audit(db,user,'framework.drafted',f.id,null,{module:b.module_id,version:b.version});return f;});}
export async function approveFramework(user,id,body){if(!user.is_admin)fail(403,'Administrator access required');const b=z.object({reason:v.short,content_reviewed:z.literal(true),scale_confirmed:z.literal(true)}).parse(body);return transaction(async db=>{const f=(await db.query('SELECT * FROM frameworks WHERE id=$1 FOR UPDATE',[v.id.parse(id)])).rows[0];if(!f)fail(404,'Framework not found');if(f.status==='Approved')fail(409,'Framework is already approved');v.frameworkSchema.parse({module_id:f.module_id,version:f.version,definition:f.definition});const cs=f.definition.domains.flatMap(d=>d.criteria);for(const policy of [f.definition.stageRules,...f.definition.domains.map(d=>d.stageRules).filter(Boolean)]){for(const gate of policy.gates){if(!cs.find(c=>c.id===gate.criterionId&&c.critical)||gate.status!=='Approved')fail(409,'Gates require explicitly critical criteria and approved rationale/source');}if(policy.bands.length){const bands=policy.bands; if(bands.length!==5||bands.some((b,i)=>b.level!==i+1||(i===0?b.minimum!==1:b.minimum<=bands[i-1].minimum)))fail(400,'Stage thresholds must define five increasing bands starting at 1');}}
  await db.query("UPDATE frameworks SET status='Approved',approved_by=$1,approved_at=now() WHERE id=$2",[user.id,id]);await audit(db,user,'framework.approved',id,{status:'Draft'},{status:'Approved'},null,null,b.reason);return {ok:true};});}
export async function updateRoadmap(user,assessmentId,id,body){const b=z.object({revision:z.number().int(),status:z.enum(['Not Started','In Progress','Completed','On Hold']),reason:v.short}).parse(body);return mutate(user,assessmentId,mutableRoles,async(db,a)=>{const r=(await db.query('SELECT * FROM roadmap WHERE id=$1 AND assessment_id=$2',[v.id.parse(id),a.id])).rows[0];if(!r)fail(404,'Initiative not found');revision(r,b.revision);await db.query('UPDATE roadmap SET status=$1,revision=revision+1 WHERE id=$2',[b.status,id]);await audit(db,user,'roadmap.status',id,r,b,a.client_id,a.id,b.reason);return {ok:true};},true);}
export async function linkAsset(user,assessmentId,recommendationId,body){const {knowledge_id}=z.object({knowledge_id:v.id}).parse(body);return mutate(user,assessmentId,mutableRoles,async(db,a)=>{const r=(await db.query('SELECT id FROM recommendations WHERE id=$1 AND assessment_id=$2',[v.id.parse(recommendationId),a.id])).rows[0];if(!r)fail(404,'Recommendation not found');await db.query('INSERT INTO recommendation_assets(recommendation_id,knowledge_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[r.id,knowledge_id]);await audit(db,user,'recommendation.asset',r.id,null,{knowledge_id},a.client_id,a.id);return {ok:true};});}
export async function addDependency(user,assessmentId,initiativeId,body){const {dependency_id}=z.object({dependency_id:v.id}).parse(body);v.id.parse(initiativeId);return mutate(user,assessmentId,mutableRoles,async(db,a)=>{
  if(initiativeId===dependency_id)fail(400,'An initiative cannot depend on itself');
  const nodes=(await db.query('SELECT id FROM roadmap WHERE assessment_id=$1 AND id=ANY($2::uuid[])',[a.id,[initiativeId,dependency_id]])).rows;if(nodes.length!==2)fail(404,'Both initiatives must belong to this assessment');
  const edges=(await db.query('SELECT initiative_id,dependency_id FROM roadmap_dependencies WHERE assessment_id=$1',[a.id])).rows;
  const pending=[dependency_id],seen=new Set();while(pending.length){const id=pending.pop();if(id===initiativeId)fail(409,'This dependency would create a cycle');if(seen.has(id))continue;seen.add(id);pending.push(...edges.filter(e=>e.initiative_id===id).map(e=>e.dependency_id));}
  await db.query('INSERT INTO roadmap_dependencies(initiative_id,dependency_id,assessment_id,client_id) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[initiativeId,dependency_id,a.id,a.client_id]);await audit(db,user,'roadmap.dependency',initiativeId,null,{dependency_id},a.client_id,a.id);return {ok:true};
});}
export async function compareAssessments(user,leftId,rightId){
  const left=await assessment({query},user,leftId),right=await assessment({query},user,rightId);
  if(left.client_id!==right.client_id)fail(400,'Compare assessments of the same client');
  const reports=[];for(const id of [leftId,rightId]){const s=(await query('SELECT report FROM report_snapshots WHERE assessment_id=$1 ORDER BY approved_at DESC LIMIT 1',[id])).rows[0];if(!s)fail(409,'Comparison requires two approved assessment snapshots');reports.push(s.report);}
  const [a,b]=reports,key=r=>r.frameworks.map(f=>f.id).sort().join('|');if(key(a)!==key(b))fail(409,'Framework versions and module scope must match for a valid comparison');
  return {left:a.assessment,right:b.assessment,rows:a.results.modules.flatMap(m=>m.domains.map(d=>{const next=b.results.modules.find(x=>x.id===m.id).domains.find(x=>x.id===d.id);return {domain:d.title,previous:d.score,current:next.score,change:Number(next.score)-Number(d.score)};}))};
}
