import {z} from 'zod';
export const text=z.string().trim().max(10000);
export const short=z.string().trim().min(1).max(250);
export const id=z.uuid();
export const score=z.number().int().min(1).max(5);
const date=z.iso.date();
export const clientSchema=z.object({name:short,sector:short,organization_type:text.default(''),country:text.default(''),city:text.default(''),size:text.default(''),employee_count:z.number().int().min(0).nullable().default(null),sponsor:text.default(''),contact:text.default(''),notes:text.default('')}).strict();
export const assessmentSchema=z.object({client_id:id,title:short,assessment_date:date,participants:text.default(''),assessment_type:short.default('Consultant-led'),framework_ids:z.array(id).min(1).max(20)}).strict();
export const responseSchema=z.object({revision:z.number().int().min(0),answers:z.record(z.string(),score),comment:text,internal_notes:text,confidence:z.enum(['Low','Medium','High']).nullable(),confidence_rationale:text}).strict();
export const reviewSchema=z.object({revision:z.number().int(),score,status:z.enum(['Approved','Returned']),rationale:short}).strict();
export const targetSchema=z.object({revision:z.number().int(),target:score.nullable(),rationale:short}).strict();
export const evidenceSchema=z.object({title:short,kind:z.enum(['PDF','Word','Excel','PowerPoint','Image','URL','Interview notes','Workshop notes','System extract','Meeting record']),description:text,source:text,owner:text,evidence_date:date.nullable(),url:z.url().refine(v=>['http:','https:'].includes(new URL(v).protocol)).nullable(),response_ids:z.array(id).min(1).max(100),file:z.object({name:short,mime:short,base64:z.string().max(2800000)}).optional()}).strict();
export const findingSchema=z.object({response_id:id,title:short,description:short,condition:text,root_cause:text,consequence:text,severity:z.enum(['Critical','High','Medium','Low']),priority:z.enum(['Critical','High','Medium','Low'])}).strict();
export const recommendationSchema=z.object({response_id:id,finding_id:id.nullable().default(null),title:short,action:short,rationale:short,approach:short,deliverables:short,owner:text,priority:z.enum(['Critical','High','Medium','Low']),impact:text,effort:text,horizon:short,source_location:short}).strict();
export const roadmapSchema=z.object({recommendation_id:id,title:short,objective:short,actions:short,deliverable:short,owner:short,start_month:z.number().int().min(0).max(120),end_month:z.number().int().min(0).max(120),priority:z.enum(['Critical','High','Medium','Low']),impact:text,effort:text}).strict().refine(v=>v.end_month>=v.start_month,'End period precedes start period');
export const lessonSchema=z.object({title:short,recurring_gap:text,root_cause:text,action:text,worked:text,did_not_work:text,outcome:text,notes:text,reusable:z.boolean()}).strict();
const sourceSchema=z.object({title:short,location:short,type:short,verifiedAt:short,url:z.url().optional(),hash:text.optional(),derivation:short}).passthrough();
const gateSchema=z.object({criterionId:short,minimum:score,cap:score,rationale:short,source:short,status:z.enum(['Draft','Approved'])}).strict();
const stageSchema=z.object({bands:z.array(z.object({level:score,minimum:z.number().min(1).max(5)})),gates:z.array(gateSchema)});
const criterionSchema=z.object({id:short,title:short,weight:z.number().positive(),questions:z.array(z.object({id:short,weight:z.number().positive(),text:short})).min(1),descriptors:z.object({'1':short,'2':short,'3':short,'4':short,'5':short}),guidance:text,evidenceRequired:short,source:sourceSchema,critical:z.boolean()}).passthrough();
export const frameworkSchema=z.object({module_id:z.enum(['strategy','pmo','kpi']),version:short,definition:z.object({title:short,levels:z.array(short).length(5),allowNA:z.literal(false),stageRules:stageSchema,domains:z.array(z.object({id:short,title:short,weight:z.number().positive(),criteria:z.array(criterionSchema).min(1),stageRules:stageSchema.optional()})).min(1)}).passthrough()}).strict();
